main:
      - name: Contact
        url: contact/
        weight: 30
      - name: Articles
        url: articles/
        weight: 20
      - name: Projects
        url: projects/
        weight: 15

    # - name: Categories
      #   url: categories/
      #   weight: 10
      # - name: new Tab
      #   url: mewtab/
      #   weight: defines order of tabs